import React, { useEffect, useRef, useState } from 'react'
import { Archive, Bell, Camera, Check, CircleUserRound, CreditCard, Crown, KeyRound, LifeBuoy, Mail, Moon, Palette, Plus, Rocket, Shield, Sparkles, Sun, Swords, Target, Trash2 } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { useApp } from '../context/AppContext'
import { removeProfilePicture, saveProfile, uploadProfilePicture } from '../lib/data'
import { appUrl, supabase } from '../lib/supabase'
import { isIsrEmail, SCHOOL_OPTIONS } from '../lib/schools'
import { LEARNING_GOALS, LEARNING_LEVELS } from '../lib/personalization'
import { Button, Field, Modal, PageHeading, ProfileAvatar } from '../components/UI'

const subjectColors = ['#2692f5', '#2fc77b', '#9a5cf0', '#ffad2f', '#f04d92', '#16b8b1']
const schoolSystems = ['British', 'American', 'IB', 'German / Abitur', 'IGCSE', 'GCSE', 'A-Level', 'Abitur', 'AP', 'Other']

export default function Settings() {
  const { user, profile, data, refresh, notify, theme, setTheme, create, update, remove } = useApp()
  const navigate = useNavigate()
  const avatarInput = useRef()
  const [draft, setDraft] = useState({ display_name: profile?.display_name || '', grade_year: profile?.grade_year || '', school_system: profile?.school_system || '', school: profile?.school || '', timezone: profile?.timezone || Intl.DateTimeFormat().resolvedOptions().timeZone }), [saving, setSaving] = useState(false), [resetting, setResetting] = useState(false), [billing, setBilling] = useState(false), [uploadingAvatar, setUploadingAvatar] = useState(false), [removingAvatar, setRemovingAvatar] = useState(false), [subjectModal, setSubjectModal] = useState(false), [subjectToDelete, setSubjectToDelete] = useState(null), [deletingSubject, setDeletingSubject] = useState(false), [deleteModal, setDeleteModal] = useState(false)
  const [learningDraft, setLearningDraft] = useState({ level: Number(user?.user_metadata?.learning_preferences?.level ?? 1), subjects: user?.user_metadata?.learning_preferences?.struggling_subjects || [], goals: profile?.goals || user?.user_metadata?.learning_preferences?.goals || [] }), [learningSaving, setLearningSaving] = useState(false)
  useEffect(() => { if (profile) setDraft({ display_name: profile.display_name || '', grade_year: profile.grade_year || '', school_system: profile.school_system || '', school: profile.school || '', timezone: profile.timezone || Intl.DateTimeFormat().resolvedOptions().timeZone }) }, [profile?.id, profile?.school])
  useEffect(() => { setLearningDraft({ level: Number(user?.user_metadata?.learning_preferences?.level ?? 1), subjects: user?.user_metadata?.learning_preferences?.struggling_subjects || [], goals: profile?.goals || user?.user_metadata?.learning_preferences?.goals || [] }) }, [profile?.goals, user?.user_metadata?.learning_preferences])
  const subjects = data?.subjects || []
  const subscription = data?.subscriptions?.[0]
  const save = async event => { event.preventDefault(); setSaving(true); try { await saveProfile(user.id, draft); await refresh(); notify('Profile updated.') } catch (error) { notify(error.message, 'error') } finally { setSaving(false) } }
  const togglePref = async (key, value) => { try { await saveProfile(user.id, { [key]: value }); await refresh(); notify('Preference saved.') } catch (error) { notify(error.message, 'error') } }
  const deleteAccount = async () => { const { data: sessionData } = await supabase.auth.getSession(); const response = await fetch('/api/account', { method: 'DELETE', headers: { Authorization: `Bearer ${sessionData.session?.access_token || ''}` } }); if (!response.ok) { const result = await response.json(); return notify(result.error || 'Unable to delete account.', 'error') } await supabase.auth.signOut() }
  const chooseTheme = async value => { setTheme(value); try { await saveProfile(user.id, { theme_preference: value }); await refresh() } catch (error) { notify(error.message, 'error') } }
  const sendPasswordReset = async () => { setResetting(true); try { const { error } = await supabase.auth.resetPasswordForEmail(user.email, { redirectTo: appUrl('/reset-password') }); if (error) throw error; notify('Password reset email sent.') } catch (error) { notify(error.message || 'Unable to send the password reset email.', 'error') } finally { setResetting(false) } }
  const manageBilling = async () => { setBilling(true); try { const { data: sessionData } = await supabase.auth.getSession(); const response = await fetch('/api/stripe/portal', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${sessionData.session?.access_token || ''}` } }); const result = await response.json(); if (!response.ok) throw new Error(result.error); location.assign(result.url) } catch (error) { notify(error.message || 'Unable to open billing management.', 'error'); setBilling(false) } }
  const uploadAvatar = async event => { const file = event.target.files?.[0]; if (!file) return; setUploadingAvatar(true); try { await uploadProfilePicture({ userId: user.id, file }); await refresh(); notify('Profile picture updated and linked to your leaderboard profile.') } catch (error) { notify(error.message || 'Unable to upload the profile picture.', 'error') } finally { setUploadingAvatar(false); event.target.value = '' } }
  const removeAvatar = async () => { setRemovingAvatar(true); try { await removeProfilePicture(); await refresh(); notify('Profile picture removed.') } catch (error) { notify(error.message || 'Unable to remove the profile picture.', 'error') } finally { setRemovingAvatar(false) } }
  const toggleLearning = (key, value) => setLearningDraft(current => ({ ...current, [key]: current[key].includes(value) ? current[key].filter(item => item !== value) : [...current[key], value] }))
  const saveLearning = async () => { setLearningSaving(true); try { await saveProfile(user.id, { goals: learningDraft.goals }); await supabase.auth.updateUser({ data: { learning_preferences: { level: learningDraft.level, struggling_subjects: learningDraft.subjects, goals: learningDraft.goals } } }); await refresh(); notify('Learning preferences updated.') } catch (error) { notify(error.message || 'Unable to update your learning preferences.', 'error') } finally { setLearningSaving(false) } }
  const startTutorial = () => { localStorage.setItem(`studentley-product-tour-${user.id}`, 'active'); localStorage.setItem(`studentley-product-tour-step-${user.id}`, '0'); window.dispatchEvent(new CustomEvent('studentley:start-tutorial')); navigate('/app') }
  const deleteSubject = async () => { if (!subjectToDelete) return; setDeletingSubject(true); try { await remove('subjects', subjectToDelete.id); notify(`${subjectToDelete.name} deleted.`); setSubjectToDelete(null) } catch (error) { notify(error.message || 'Unable to delete the subject.', 'error') } finally { setDeletingSubject(false) } }
  return <>
    <PageHeading eyebrow="Settings" title="Make Studentley yours" text="Manage your profile, subjects, preferences, privacy and account." />
    <div className="settings-layout"><section className="card settings-card"><div className="settings-title"><span className="icon-bubble blue"><CircleUserRound /></span><div><h2>Profile</h2><p>Your private account information.</p></div></div><div className="profile-picture-settings"><ProfileAvatar user={user} name={draft.display_name || 'Student'} className="profile-avatar-large" /><div><b>Profile picture</b><p>Shown to signed-in students on the leaderboard when you join it · JPG or PNG · maximum 5 MB</p><div className="inline-actions"><Button type="button" variant="secondary" loading={uploadingAvatar} onClick={() => avatarInput.current?.click()}><Camera /> {user?.user_metadata?.avatar_path ? 'Change picture' : 'Upload picture'}</Button>{user?.user_metadata?.avatar_path && <Button type="button" variant="ghost" loading={removingAvatar} onClick={removeAvatar}>Remove</Button>}</div><input ref={avatarInput} hidden type="file" accept="image/jpeg,image/png" onChange={uploadAvatar} /></div></div><form onSubmit={save}><div className="form-grid"><Field label="Name"><input value={draft.display_name} onChange={e => setDraft({ ...draft, display_name: e.target.value })} /></Field><Field label="Grade or year"><input value={draft.grade_year} onChange={e => setDraft({ ...draft, grade_year: e.target.value })} /></Field><Field label="School system"><select value={draft.school_system} onChange={e => setDraft({ ...draft, school_system: e.target.value })}><option value="">Choose one</option>{schoolSystems.map(item => <option key={item}>{item}</option>)}</select></Field><Field label="School" hint={draft.school === 'ISR' ? isIsrEmail(user?.email) ? 'Your ISR email qualifies this account for Plus School.' : 'Plus School requires a five-digit @isr-school.de account email.' : 'Enter your school name or leave it empty.'}><input list="studentley-school-options" value={draft.school || ''} onChange={e => setDraft({ ...draft, school: e.target.value })} placeholder="School name (optional)" /><datalist id="studentley-school-options">{SCHOOL_OPTIONS.map(option => <option value={option.value} key={option.value}>{option.label}</option>)}</datalist></Field><Field label="Timezone"><input value={draft.timezone} readOnly /></Field></div><Field label="Email" hint="Email changes require verification."><input value={user?.email || ''} readOnly /></Field><Button loading={saving}>Save profile</Button></form></section>
      <section className="card settings-card"><div className="settings-title"><span className="icon-bubble violet"><Palette /></span><div><h2>Appearance</h2><p>Choose a calm workspace in any light.</p></div></div><div className="theme-options">{[['light', Sun, 'Light'], ['dark', Moon, 'Dark'], ['system', Palette, 'System']].map(([id, Icon, label]) => <button className={theme === id ? 'selected' : ''} onClick={() => chooseTheme(id)} key={id}><Icon /><b>{label}</b>{theme === id && <Check />}</button>)}</div><div className="settings-title subsection"><span className="icon-bubble green"><Bell /></span><div><h2>Notifications</h2><p>Use reminders that help, not distract.</p></div></div>{profile?.subscription_plan === 'pro' ? <Toggle label="Study reminders" text="Get an in-app reminder 30 minutes before a planned session." value={profile?.study_reminders} onChange={value => togglePref('study_reminders', value)} /> : <div className="toggle-locked"><Crown /><span><b>Study reminders</b><small>Study reminders are exclusive to Pro.</small></span><button onClick={() => navigate('/plans')} aria-label="View Pro plan"><Crown /></button></div>}<Toggle label="Exam reminders" text="Alert me as real exam dates approach." value={profile?.exam_reminders ?? true} onChange={value => togglePref('exam_reminders', value)} /><Toggle label="Achievement updates" text="Tell me when genuine progress unlocks an achievement." value={profile?.achievement_notifications ?? true} onChange={value => togglePref('achievement_notifications', value)} /></section>
      <section className="card settings-card subjects-settings"><div className="section-heading"><div className="settings-title"><span className="icon-bubble orange"><CreditCard /></span><div><h2>Subjects</h2><p>Keep only what you’re actually studying.</p></div></div><Button variant="secondary" onClick={() => setSubjectModal(true)}><Plus /> Add</Button></div><div className="subject-list">{subjects.map(subject => <div className={subject.archived_at ? 'archived' : ''} key={subject.id}><i style={{ background: subject.color }} /><span><b>{subject.name}</b><small>{subject.archived_at ? 'Archived' : 'Active'}</small></span><div className="subject-list-actions"><button onClick={() => update('subjects', subject.id, { archived_at: subject.archived_at ? null : new Date().toISOString() })} aria-label={subject.archived_at ? `Restore ${subject.name}` : `Archive ${subject.name}`}><Archive /></button><button className="subject-delete" onClick={() => setSubjectToDelete(subject)} aria-label={`Delete ${subject.name}`}><Trash2 /></button></div></div>)}</div></section>
      <section className="card settings-card settings-learning"><div className="settings-title"><span className="icon-bubble violet"><Target /></span><div><h2>Learning preferences</h2><p>Edit the answers that personalize difficulty and recommendations.</p></div></div><Field label="Current school confidence"><div className="settings-level"><input type="range" min="0" max="3" step="1" value={learningDraft.level} onChange={event => setLearningDraft({ ...learningDraft, level: Number(event.target.value) })} /><b>{LEARNING_LEVELS[learningDraft.level]?.label}</b></div></Field><Field label="Subjects where you want more support"><div className="settings-choice-cloud">{subjects.filter(subject => !subject.archived_at).map(subject => <button type="button" className={learningDraft.subjects.includes(subject.name) ? 'selected' : ''} onClick={() => toggleLearning('subjects', subject.name)} key={subject.id}>{subject.name}{learningDraft.subjects.includes(subject.name) && <Check />}</button>)}</div></Field><Field label="Learning goals"><div className="settings-choice-cloud">{LEARNING_GOALS.map(goal => <button type="button" className={learningDraft.goals.includes(goal) ? 'selected' : ''} onClick={() => toggleLearning('goals', goal)} key={goal}>{goal}{learningDraft.goals.includes(goal) && <Check />}</button>)}</div></Field><Button loading={learningSaving} onClick={saveLearning}>Save learning preferences</Button></section>
      <section className="card settings-card"><div className="settings-title"><span className="icon-bubble green"><CreditCard /></span><div><h2>Plan & billing</h2><p>Your subscription is verified by the server.</p></div></div><div className="current-plan"><span>{profile?.school_plan ? 'School' : profile?.subscription_plan || 'Free'}</span><div><b>{profile?.school_plan ? 'Plus School' : profile?.subscription_plan || 'Free'} plan</b><p>{profile?.school_plan ? 'Plus access is included with your verified ISR account email.' : profile?.subscription_plan === 'free' || !profile?.subscription_plan ? 'Explore more features when you need them.' : 'Manage your secure Stripe subscription.'}</p></div></div><div className="inline-actions"><Button variant="secondary" onClick={() => navigate('/plans')}>Compare plans</Button>{subscription?.stripe_customer_id && <Button loading={billing} onClick={manageBilling}>Manage billing</Button>}</div><div className="settings-title subsection"><span className="icon-bubble violet"><Sparkles /></span><div><h2>Leaderboard</h2><p>Control whether your profile appears in the Studentley League.</p></div></div><Toggle label="Join the leaderboard" text="Your first name, profile picture, plan badge, points and streak are shared with signed-in students." value={profile?.leaderboard_visible ?? true} onChange={value => togglePref('leaderboard_visible', value)} /><div className="settings-title subsection"><span className="icon-bubble blue"><KeyRound /></span><div><h2>Security</h2><p>Password and account controls.</p></div></div><Button type="button" variant="secondary" loading={resetting} onClick={sendPasswordReset}>Send password reset email</Button></section>
      <section className="card settings-card settings-rivals"><div className="settings-title"><span className="icon-bubble green"><Swords /></span><div><h2>Studentley Rivals</h2><p>Switch to the separate competitive dashboard for ranked matches, friend battles and public quizzes.</p></div></div><Button className="rivals-settings-button" onClick={() => navigate('/rivals')}><Swords /> Enter Rivals</Button></section>
      <section className="card settings-card settings-support"><div className="settings-title"><span className="icon-bubble violet"><LifeBuoy /></span><div><h2>Need help?</h2><p>Replay the tour or contact Studentley support directly.</p></div></div><Button variant="secondary" onClick={startTutorial}><Rocket /> Replay website tutorial</Button><div className="support-contact"><span><Mail /></span><div><b>Studentley Support</b><a href="mailto:support@studentley.com">support@studentley.com</a><p>Include the page you were using and a short description of the problem.</p></div></div><a className="button secondary" href="mailto:support@studentley.com?subject=Studentley%20support%20request"><Mail /> Contact support</a></section>
    </div>
    <section className="card danger-zone"><div><Shield /><span><b>Privacy and account</b><p>Your date of birth, school data and documents are never public.</p></span></div><Button variant="danger" onClick={() => setDeleteModal(true)}><Trash2 /> Delete account</Button></section>
    {subjectModal && <SubjectModal userId={user.id} onClose={() => setSubjectModal(false)} create={create} notify={notify} />}{subjectToDelete && <Modal title={`Delete ${subjectToDelete.name}?`} description="This removes the subject permanently. Linked topics, exams, documents and practice stay saved without a subject; timetable entries for it are removed." onClose={() => !deletingSubject && setSubjectToDelete(null)}><div className="inline-actions"><Button variant="secondary" disabled={deletingSubject} onClick={() => setSubjectToDelete(null)}>Cancel</Button><Button variant="danger" loading={deletingSubject} onClick={deleteSubject}><Trash2 /> Delete subject</Button></div></Modal>}{deleteModal && <Modal title="Delete your account?" description="This permanently removes your profile, school data and uploaded files. It cannot be undone." onClose={() => setDeleteModal(false)}><Button variant="danger" className="full" onClick={deleteAccount}>Permanently delete my account</Button></Modal>}
  </>
}

function Toggle({ label, text, value, onChange }) { return <div className="toggle-row"><span><b>{label}</b><small>{text}</small></span><button role="switch" aria-checked={Boolean(value)} className={value ? 'on' : ''} onClick={() => onChange(!value)}><i /></button></div> }
function SubjectModal({ userId, onClose, create, notify }) { const [name, setName] = useState(''), [color, setColor] = useState(subjectColors[0]), [saving, setSaving] = useState(false); const submit = async event => { event.preventDefault(); setSaving(true); try { await create('subjects', { user_id: userId, name: name.trim(), color, icon: 'book' }); notify('Subject added.'); onClose() } finally { setSaving(false) } }; return <Modal title="Add subject" onClose={onClose}><form onSubmit={submit}><Field label="Subject name"><input autoFocus required value={name} onChange={e => setName(e.target.value)} /></Field><Field label="Colour"><div className="color-picker">{subjectColors.map(value => <button type="button" className={color === value ? 'selected' : ''} style={{ background: value }} onClick={() => setColor(value)} key={value}>{color === value && <Check />}</button>)}</div></Field><Button className="full" loading={saving}>Add subject</Button></form></Modal> }
