import React, { useMemo, useState } from 'react'
import { CalendarDays, Check, ChevronLeft, ChevronRight, Crown, LayoutGrid, ListTodo, Pencil, Plus, Sparkles, Trash2 } from 'lucide-react'
import { useApp } from '../context/AppContext'
import { generateStudyPlan } from '../services/ai'
import { Button, EmptyState, Field, Modal, PageHeading, UpgradeModal, formatDate } from '../components/UI'

const todayInput = (hour = 16) => { const date = new Date(); date.setHours(hour, 0, 0, 0); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16) }
const weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

export default function StudyPlan() {
  const { user, data, create, update, remove, notify, profile, refresh } = useApp()
  const [tab, setTab] = useState('week'), [modal, setModal] = useState(null), [ai, setAi] = useState(false), [upgrade, setUpgrade] = useState(false), [weekOffset, setWeekOffset] = useState(0)
  const currentPlan = profile?.subscription_plan || 'free'
  const subjects = data?.subjects?.filter(item => !item.archived_at) || [], sessions = data?.study_sessions || [], tasks = data?.tasks || [], timetable = data?.timetable_entries || []
  const week = useMemo(() => { const start = new Date(); const day = start.getDay() || 7; start.setDate(start.getDate() - day + 1 + weekOffset * 7); start.setHours(0, 0, 0, 0); return Array.from({ length: 7 }, (_, i) => { const value = new Date(start); value.setDate(start.getDate() + i); return value }) }, [weekOffset])
  const saveSession = async draft => { const payload = { title: draft.title, subject_id: draft.subject_id || null, starts_at: new Date(draft.starts_at).toISOString(), duration_minutes: Number(draft.duration), notes: draft.notes || null }; draft.id ? await update('study_sessions', draft.id, payload) : await create('study_sessions', { user_id: user.id, ...payload }); setModal(null); notify(draft.id ? 'Study session updated.' : 'Study session added.') }
  const saveTask = async draft => { const payload = { title: draft.title, subject_id: draft.subject_id || null, due_at: draft.due_at ? new Date(draft.due_at).toISOString() : null, priority: draft.priority, notes: draft.notes || null }; draft.id ? await update('tasks', draft.id, payload) : await create('tasks', { user_id: user.id, ...payload }); setModal(null); notify(draft.id ? 'Task updated.' : 'Task added.') }
  const saveClass = async draft => { const payload = { subject_id: draft.subject_id, day_of_week: Number(draft.day), start_time: draft.start_time, end_time: draft.end_time, classroom: draft.classroom || null }; draft.id ? await update('timetable_entries', draft.id, payload) : await create('timetable_entries', { user_id: user.id, ...payload }); setModal(null); notify(draft.id ? 'Class updated.' : 'Class added.') }
  const complete = async (table, item) => { await update(table, item.id, { completed_at: item.completed_at ? null : new Date().toISOString() }); notify(item.completed_at ? 'Item reopened.' : 'Marked complete.') }
  const removeItem = async (table, item) => { if (!window.confirm(`Delete “${item.title || 'this class'}”?`)) return; await remove(table, item.id); notify('Item deleted.') }
  return <>
    <PageHeading eyebrow="Your week" title="Study plan" text="Plan real work around your schedule and keep momentum visible." actions={<><Button variant="secondary" onClick={() => currentPlan === 'free' ? setUpgrade(true) : setAi(true)}>{currentPlan === 'free' ? <Crown /> : <Sparkles />} Personalize with AI {currentPlan === 'free' && <small className="premium-label">Plus</small>}</Button><Button onClick={() => setModal('session')}><Plus /> Add session</Button></>} />
    {currentPlan === 'free' && <div className="plan-banner"><span><Sparkles /></span><div><b>Basic study plan</b><p>Manual planning is fully available. AI personalization is included with Plus and Pro.</p></div></div>}
    <div className="tabs" role="tablist">{[['week', CalendarDays, 'Week'], ['tasks', ListTodo, 'Tasks'], ['timetable', LayoutGrid, 'Timetable']].map(([id, Icon, label]) => <button role="tab" aria-selected={tab === id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)} key={id}><Icon />{label}</button>)}</div>
      {tab === 'week' && <section className="card week-card"><header className="week-header"><div><h2>{formatDate(week[0], { month: 'long' })}</h2><p>{formatDate(week[0])} – {formatDate(week[6])}</p></div><div><button onClick={() => setWeekOffset(value => value - 1)} aria-label="Previous week"><ChevronLeft /></button><Button variant="ghost" onClick={() => setWeekOffset(0)}>Today</Button><button onClick={() => setWeekOffset(value => value + 1)} aria-label="Next week"><ChevronRight /></button></div></header><div className="week-grid">{week.map(day => { const daySessions = sessions.filter(item => new Date(item.starts_at).toDateString() === day.toDateString()).sort((a, b) => new Date(a.starts_at) - new Date(b.starts_at)); return <div className={`day-column ${day.toDateString() === new Date().toDateString() ? 'today' : ''}`} key={day.toISOString()}><header><small>{day.toLocaleDateString([], { weekday: 'short' })}</small><b>{day.getDate()}</b></header><div>{daySessions.map(item => <article className={`session-chip ${item.completed_at ? 'done' : ''}`} style={{ '--subject': item.subjects?.color || '#2692f5' }} key={item.id}><time>{new Date(item.starts_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time><b>{item.title}</b><small>{item.duration_minutes} min</small><div><button onClick={() => complete('study_sessions', item)} aria-label="Toggle completion"><Check /></button><button onClick={() => setModal({ type: 'session', item })} aria-label="Edit session"><Pencil /></button><button onClick={() => removeItem('study_sessions', item)} aria-label="Delete session"><Trash2 /></button></div></article>)}</div>{!daySessions.length && <button className="add-day" onClick={() => setModal({ type: 'session', date: day })}>+</button>}</div> })}</div>{!sessions.length && <EmptyState icon={CalendarDays} title="No study sessions yet" text="Create your first session and build a plan around your actual week."><Button onClick={() => setModal('session')}>Add a study session</Button></EmptyState>}</section>}
    {tab === 'tasks' && <section className="card list-card"><div className="section-heading"><div><h2>Tasks</h2><p>Assignments, homework and personal study goals.</p></div><Button onClick={() => setModal('task')}><Plus /> Add task</Button></div>{tasks.length ? <div className="task-list">{tasks.map(item => <article className={item.completed_at ? 'completed' : ''} key={item.id}><button className="task-check" onClick={() => complete('tasks', item)}>{item.completed_at && <Check />}</button><div><b>{item.title}</b><p>{item.subjects?.name || 'No subject'}{item.due_at ? ` · Due ${formatDate(item.due_at)}` : ''}</p></div><span className={`priority ${item.priority}`}>{item.priority}</span><button className="round-button" onClick={() => setModal({ type: 'task', item })} aria-label="Edit task"><Pencil /></button><button className="delete-button" onClick={() => removeItem('tasks', item)}><Trash2 /></button></article>)}</div> : <EmptyState icon={ListTodo} title="No tasks yet" text="Add an assignment, deadline or study goal."><Button onClick={() => setModal('task')}>Add your first task</Button></EmptyState>}</section>}
    {tab === 'timetable' && <section className="card timetable-card"><div className="section-heading"><div><h2>Weekly timetable</h2><p>Add classes manually. Weekend columns appear when you use them.</p></div><Button onClick={() => setModal('class')}><Plus /> Add class</Button></div>{timetable.length ? <div className="timetable-grid">{weekdays.slice(0, timetable.some(item => item.day_of_week > 5) ? 7 : 5).map((day, index) => <div key={day}><h3>{day}</h3>{timetable.filter(item => item.day_of_week === index + 1).sort((a, b) => a.start_time.localeCompare(b.start_time)).map(item => <article key={item.id} style={{ '--subject': item.subjects?.color || '#2692f5' }}><time>{item.start_time.slice(0,5)}–{item.end_time.slice(0,5)}</time><b>{item.subjects?.name || 'Class'}</b>{item.classroom && <small>{item.classroom}</small>}<span className="class-actions"><button onClick={() => setModal({ type: 'class', item })} aria-label="Edit class"><Pencil /></button><button onClick={() => removeItem('timetable_entries', { ...item, title: item.subjects?.name })} aria-label="Delete class"><Trash2 /></button></span></article>)}</div>)}</div> : <EmptyState icon={LayoutGrid} title="Your timetable is empty" text="Add classes manually, or upload a timetable and import it with AI."><div className="inline-actions"><Button onClick={() => setModal('class')}>Add a class</Button><Button variant="secondary" onClick={() => location.assign('/upload')}>Upload timetable</Button></div></EmptyState>}</section>}
    {modal && <PlannerModal type={typeof modal === 'string' ? modal : modal.type} date={modal.date} initial={modal.item} subjects={subjects} onClose={() => setModal(null)} onSession={saveSession} onTask={saveTask} onClass={saveClass} />}{ai && <StudyPlanAiModal profile={profile} onClose={() => setAi(false)} onGenerated={async result => { await refresh(); setAi(false); setWeekOffset(0); notify(`${result.imported} personalized study sessions added.`) }} />}{upgrade && <UpgradeModal feature="Personalized study plan" onClose={() => setUpgrade(false)} />}
  </>
}

function StudyPlanAiModal({ profile, onClose, onGenerated }) {
  const defaultDate = () => { const value = new Date(); const day = value.getDay() || 7; value.setDate(value.getDate() - day + 8); return value.toISOString().slice(0, 10) }
  const [draft, setDraft] = useState({ weekStart: defaultDate(), dailyMinutes: profile?.daily_study_minutes || 45, focus: '' })
  const [loading, setLoading] = useState(false), [error, setError] = useState('')
  const submit = async event => { event.preventDefault(); setLoading(true); setError(''); try { const result = await generateStudyPlan({ weekStart: draft.weekStart, dailyMinutes: Number(draft.dailyMinutes), focus: draft.focus.trim() }); await onGenerated(result) } catch (problem) { setError(problem.message || 'The study plan could not be generated.') } finally { setLoading(false) } }
  return <Modal title="Personalize your week with AI" description="Studentley uses your subjects, timetable, existing sessions and upcoming exams to build a realistic plan." onClose={onClose}><form onSubmit={submit}><Field label="Week starts"><input type="date" required min={new Date().toISOString().slice(0, 10)} value={draft.weekStart} onChange={event => setDraft({ ...draft, weekStart: event.target.value })} /></Field><Field label="Daily study target"><select value={draft.dailyMinutes} onChange={event => setDraft({ ...draft, dailyMinutes: event.target.value })}>{[30,45,60,90,120].map(value => <option value={value} key={value}>{value} minutes</option>)}</select></Field><Field label="Priority focus" hint="Optional — upcoming exams are included automatically."><textarea value={draft.focus} onChange={event => setDraft({ ...draft, focus: event.target.value })} placeholder="e.g. Focus more on maths and chemistry" /></Field>{error && <p className="ai-error">{error}</p>}<Button className="full" loading={loading}>Create my study plan</Button></form></Modal>
}

function PlannerModal({ type, date, initial, subjects, onClose, onSession, onTask, onClass }) {
  const dateValue = date ? (() => { const value = new Date(date); value.setHours(16); return new Date(value.getTime() - value.getTimezoneOffset() * 60000).toISOString().slice(0, 16) })() : todayInput()
  const localInput = value => value ? new Date(new Date(value).getTime() - new Date(value).getTimezoneOffset() * 60000).toISOString().slice(0,16) : ''
  const [draft, setDraft] = useState(initial ? type === 'session' ? { ...initial, starts_at: localInput(initial.starts_at), duration: initial.duration_minutes } : type === 'task' ? { ...initial, due_at: localInput(initial.due_at) } : { ...initial, day: initial.day_of_week } : type === 'session' ? { title: '', subject_id: '', starts_at: dateValue, duration: 45, notes: '' } : type === 'task' ? { title: '', subject_id: '', due_at: todayInput(17), priority: 'medium', notes: '' } : { subject_id: subjects[0]?.id || '', day: 1, start_time: '08:00', end_time: '09:00', classroom: '' })
  const [saving, setSaving] = useState(false)
  const submit = async event => { event.preventDefault(); setSaving(true); try { if (type === 'session') await onSession(draft); else if (type === 'task') await onTask(draft); else await onClass(draft) } finally { setSaving(false) } }
  return <Modal title={type === 'session' ? 'Add study session' : type === 'task' ? 'Add task' : 'Add class'} onClose={onClose}><form onSubmit={submit} className="modal-form">{type !== 'class' && <Field label="Title"><input required value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} placeholder={type === 'task' ? 'e.g. Finish essay outline' : 'e.g. Revise chapter 4'} /></Field>}<Field label="Subject"><select required={type === 'class'} value={draft.subject_id} onChange={e => setDraft({ ...draft, subject_id: e.target.value })}><option value="">No subject</option>{subjects.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Field>{type === 'session' && <div className="form-grid"><Field label="Starts"><input required type="datetime-local" value={draft.starts_at} onChange={e => setDraft({ ...draft, starts_at: e.target.value })} /></Field><Field label="Duration"><select value={draft.duration} onChange={e => setDraft({ ...draft, duration: e.target.value })}>{[15,30,45,60,90,120].map(value => <option value={value} key={value}>{value} minutes</option>)}</select></Field></div>}{type === 'task' && <><Field label="Due date"><input type="datetime-local" value={draft.due_at} onChange={e => setDraft({ ...draft, due_at: e.target.value })} /></Field><Field label="Priority"><select value={draft.priority} onChange={e => setDraft({ ...draft, priority: e.target.value })}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></Field></>}{type === 'class' && <><Field label="Day"><select value={draft.day} onChange={e => setDraft({ ...draft, day: e.target.value })}>{weekdays.map((day, index) => <option value={index + 1} key={day}>{day}</option>)}</select></Field><div className="form-grid"><Field label="Starts"><input type="time" value={draft.start_time} onChange={e => setDraft({ ...draft, start_time: e.target.value })} /></Field><Field label="Ends"><input type="time" value={draft.end_time} onChange={e => setDraft({ ...draft, end_time: e.target.value })} /></Field></div><Field label="Classroom (optional)"><input value={draft.classroom} onChange={e => setDraft({ ...draft, classroom: e.target.value })} /></Field></>}<Button className="full" loading={saving}>Save</Button></form></Modal>
}
