import React, { useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { generateFlashcards, generateMockExam, generateQuiz } from './services/ai'
import './styles.css'

const nav = [
  ['home', '⌂', 'Home'], ['upload', '⇧', 'Upload Document'], ['plan', '▣', 'Study Plan'],
  ['practice', '✦', 'Practice & Exams'], ['settings', '⚙', 'Settings']
]
const planInfo = {
  Free: { price: '€0', uploads: 3, exams: 1, quizzes: 5, color: 'blue' },
  Plus: { price: '€3.99', uploads: 7, exams: 5, quizzes: 30, color: 'blue' },
  Pro: { price: '€6.99', uploads: Infinity, exams: Infinity, quizzes: Infinity, color: 'violet' }
}
const initialUser = { name: 'Paul Kuchler', email: 'paul.kuchler@example.com', grade: 'Grade 8', school: 'Riverside School', plan: 'Free', uploadsUsed: 0, examsUsed: 0, quizzesUsed: 0, reminders: false }
const initialFiles = [{ id: 1, name: 'Quadratic functions.pdf', type: 'PDF', date: '22 Sep 2025', subject: 'Mathematics', status: 'Ready to study' }, { id: 2, name: 'English chapter 4 notes.docx', type: 'DOCX', date: '20 Sep 2025', subject: 'English', status: 'Ready to study' }]
const initialSessions = [
  { id: 1, time: '08:30', subject: 'Mathematics', task: 'Algebra and quadratic functions', color: 'blue', done: false },
  { id: 2, time: '10:00', subject: 'English', task: 'Reading & analysis', color: 'green', done: false },
  { id: 3, time: '14:00', subject: 'Spanish', task: 'Vocabulary practice', color: 'orange', done: false },
  { id: 4, time: '16:00', subject: 'Physics', task: 'Forces and motion', color: 'violet', done: false }
]

function useSaved(key, fallback) {
  const [value, setValue] = useState(() => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback } catch { return fallback } })
  useEffect(() => localStorage.setItem(key, JSON.stringify(value)), [key, value])
  return [value, setValue]
}
function limitLabel(value) { return value === Infinity ? 'Unlimited' : `${value} per week` }
function Icon({ children, tone = 'blue' }) { return <span className={`icon ${tone}`}>{children}</span> }

function App() {
  const [page, setPage] = useState('home')
  const [user, setUser] = useSaved('istudent-user', initialUser)
  const [files, setFiles] = useSaved('istudent-files', initialFiles)
  const [sessions, setSessions] = useSaved('istudent-sessions', initialSessions)
  const [toast, setToast] = useState('')
  const [profile, setProfile] = useState(false)
  const [menu, setMenu] = useState(false)
  const alert = (text) => { setToast(text); setTimeout(() => setToast(''), 3400) }
  const go = (next) => { setPage(next); setMenu(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const consume = (kind) => {
    const used = kind === 'uploads' ? 'uploadsUsed' : kind === 'exams' ? 'examsUsed' : 'quizzesUsed'
    if (user[used] >= planInfo[user.plan][kind]) { alert(`You've reached your weekly ${kind} limit. Upgrade to Plus for more.`); go('plans'); return false }
    setUser({ ...user, [used]: user[used] + 1 }); return true
  }
  const context = { user, setUser, files, setFiles, sessions, setSessions, alert, go, consume }
  return <div className="app-shell">
    <aside className={menu ? 'sidebar open' : 'sidebar'}>
      <button className="brand" onClick={() => go('home')}><span>iS</span><b>iStudent</b></button>
      <nav>{nav.map(([id, icon, name]) => <button key={id} className={page === id ? 'active' : ''} onClick={() => go(id)}><i>{icon}</i>{name}</button>)}</nav>
      <div className="sidebar-note"><b>✦</b><p>Small steps every day lead to big results.</p><div className="mini-progress"><span /></div><small>68%</small></div>
    </aside>
    <main>
      <header><button className="mobile-menu" onClick={() => setMenu(!menu)}>☰</button><div className="header-spacer" /><button className="bell" onClick={() => alert('You’re all caught up for today!')}>♧<em /></button><button className="profile-button" onClick={() => setProfile(true)}><span>{user.name.split(' ').map(x => x[0]).join('')}</span><div><b>{user.name}</b><small>{user.grade}</small></div><i>⌄</i></button></header>
      <section className="page">{page === 'home' && <Home {...context} />}{page === 'upload' && <Upload {...context} />}{page === 'plan' && <StudyPlan {...context} />}{page === 'practice' && <Practice {...context} />}{page === 'settings' && <Settings {...context} />}{page === 'plans' && <Plans {...context} />}</section>
    </main>
    {profile && <Profile user={user} setUser={setUser} close={() => setProfile(false)} go={go} alert={alert} />}
    {toast && <div className="toast">✓ {toast}</div>}
  </div>
}

function Home({ user, sessions, setSessions, go }) {
  const todo = sessions.filter(x => !x.done)
  return <><div className="greeting"><Icon tone="violet">☀</Icon><div><h1>Good morning, {user.name.split(' ')[0]}</h1><p>You’re on track. Let’s make today count.</p></div><span className="date-pill">▣ Mon, 22 Sep 2025</span></div>
    <div className="overview">
      <RoundCard tone="blue" icon="▤" label="Today’s tasks" value={todo.length} hint="due today" />
      <RoundCard tone="green" icon="◎" label="Study progress" value="68%" hint="of weekly goal" />
      <RoundCard tone="violet" icon="♨" label="Streak" value="5" hint="days" />
    </div>
    <div className="dashboard-grid">
      <section className="card schedule-card"><CardTitle icon="▣" title="Today’s Schedule" action="View all →" onAction={() => go('plan')} />
        {sessions.map((s) => <button className={`schedule-row ${s.done ? 'done' : ''}`} key={s.id} onClick={() => setSessions(sessions.map(x => x.id === s.id ? { ...x, done: !x.done } : x))}><span className={`dot ${s.color}`} /><div><small>{s.time} – {Number(s.time.slice(0,2)) + 1}:00</small><b>{s.subject}</b><p>{s.task}</p></div><i>{s.done ? '✓' : '›'}</i></button>)}</section>
      <section className="card exams-card"><CardTitle icon="▰" title="Upcoming Exams" action="View all →" onAction={() => go('plan')} />
        {[['25','Sep','Mathematics','Test','3 days left','green'],['02','Oct','English','Essay','10 days left','violet'],['08','Oct','Physics','Test','16 days left','orange'],['15','Oct','Spanish','Vocabulary Test','23 days left','green']].map(x => <div className="exam-row" key={x[2]}><b className={x[5]}>{x[0]}<small>{x[1]}</small></b><div><strong>{x[2]}</strong><small>{x[3]}</small></div><small>{x[4]}</small><i>›</i></div>)}
        <div className="tip"><Icon tone="violet">♕</Icon>Good preparation today leads to better results tomorrow.</div></section>
      <section className="card quick-card"><CardTitle icon="ϟ" title="Quick Actions" />
        <Action tone="blue" icon="▤" title="Upload Document" sub="Notes, PDFs, images, etc." onClick={() => go('upload')} /><Action tone="green" icon="✦" title="Generate Practice" sub="Quizzes and mock exams" onClick={() => go('practice')} /><Action tone="violet" icon="▱" title="Create Flashcards" sub="From your study material" onClick={() => go('practice')} /><Action tone="orange" icon="▣" title="View Study Plan" sub="Your personalized plan" onClick={() => go('plan')} /><Action tone="pink" icon="✧" title="Practice Exam" sub="Try a demo mock exam" onClick={() => go('practice')} /></section>
    </div></>
}
function RoundCard({ tone, icon, label, value, hint }) { return <div className={`round-card ${tone}`}><Icon tone={tone}>{icon}</Icon><b>{label}</b><strong>{value}</strong><small>{hint}</small><i>→</i></div> }
function CardTitle({ icon, title, action, onAction }) { return <div className="card-title"><Icon>{icon}</Icon><h2>{title}</h2>{action && <button onClick={onAction}>{action}</button>}</div> }
function Action({ tone, icon, title, sub, onClick }) { return <button className={`action ${tone}`} onClick={onClick}><Icon tone={tone}>{icon}</Icon><span><b>{title}</b><small>{sub}</small></span><i>›</i></button> }

function Upload({ user, setUser, files, setFiles, alert }) {
  const [subject, setSubject] = useState('Mathematics'), [drag, setDrag] = useState(false); const ref = useRef()
  const add = (selected) => { const selectedFiles = [...selected]; if (!selectedFiles.length) return; const limit = planInfo[user.plan].uploads; const remaining = limit === Infinity ? selectedFiles.length : Math.max(0, limit - user.uploadsUsed); const accepted = selectedFiles.slice(0, remaining); if (!accepted.length) { alert("You've reached your weekly upload limit. Upgrade to Plus for more."); return } setFiles(old => [...accepted.map((file, i) => ({ id: Date.now() + i, name: file.name, type: file.name.split('.').pop()?.toUpperCase() || 'FILE', date: new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }), subject, status: 'Ready to study' })), ...old]); if (limit !== Infinity) setUser({ ...user, uploadsUsed: user.uploadsUsed + accepted.length }); alert(`${accepted.length} document${accepted.length > 1 ? 's' : ''} uploaded successfully.${accepted.length < selectedFiles.length ? ' Your weekly upload limit was reached.' : ''}`) }
  return <><PageHeading eyebrow="Your material" title="Upload a document" text="Keep all your school material organised in one place." /><div className="upload-layout"><section><div className={`dropzone ${drag ? 'drag' : ''}`} onDragOver={e => { e.preventDefault(); setDrag(true) }} onDragLeave={() => setDrag(false)} onDrop={e => { e.preventDefault(); setDrag(false); add(e.dataTransfer.files) }} onClick={() => ref.current.click()}><Icon tone="blue">⇧</Icon><h2>Drop your school material here</h2><p>PDF, PPTX, images and documents</p><button className="secondary">Browse files</button><input ref={ref} type="file" multiple accept=".pdf,.ppt,.pptx,.doc,.docx,.txt,image/*" onChange={e => add(e.target.files)} /></div><label className="field">Subject <select value={subject} onChange={e => setSubject(e.target.value)}><option>Mathematics</option><option>English</option><option>Spanish</option><option>Physics</option><option>History</option></select></label></section><Usage user={user} /></div><section className="card files"><CardTitle icon="▤" title="Your documents" /><div className="file-table head"><span>Name</span><span>Subject</span><span>Uploaded</span><span>Status</span><span /></div>{files.map(file => <div className="file-table" key={file.id}><span><Icon tone="blue">▤</Icon><b>{file.name}</b><small>{file.type}</small></span><span>{file.subject}</span><span>{file.date}</span><span className="status">✓ {file.status}</span><button aria-label={`Remove ${file.name}`} onClick={() => { setFiles(files.filter(x => x.id !== file.id)); alert('Document removed.') }}>×</button></div>)}</section></>
}
function Usage({ user }) { const p = planInfo[user.plan]; const rows = [['Document uploads', 'uploads', 'uploadsUsed'], ['Mock exams', 'exams', 'examsUsed'], ['AI-style quizzes', 'quizzes', 'quizzesUsed']]; return <aside className="usage"><span className="plan-tag">{user.plan} plan</span><h3>Your weekly usage</h3>{rows.map(([name, limit, used]) => <div className="usage-row" key={limit}><div><b>{name}</b><small>{p[limit] === Infinity ? 'Unlimited' : `${user[used]} of ${p[limit]} used`}</small></div><strong>{p[limit] === Infinity ? '∞' : p[limit] - user[used]}</strong></div>)}{user.plan === 'Free' && <p>Need more room to learn? <b>Upgrade anytime.</b></p>}</aside> }

function StudyPlan({ user, sessions, setSessions, alert, go }) {
  const [modal, setModal] = useState(false), [draft, setDraft] = useState({ time: '17:00', subject: 'Mathematics', task: 'Revision session' })
  const save = () => { setSessions([...sessions, { ...draft, id: Date.now(), color: 'blue', done: false }]); setModal(false); alert('Study session added.') }
  return <><PageHeading eyebrow="Your week" title="Study plan" text="A calm, clear plan for your upcoming goals." action="Add study session" onAction={() => setModal(true)} /><div className="plan-layout"><section className="card calendar"><div className="calendar-top"><h2>September 2025</h2><div><button>‹</button><button>›</button></div></div><div className="weekdays">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((x, i) => <div className={i === 0 ? 'today' : ''} key={x}><small>{x}</small><b>{22 + i}</b></div>)}</div><div className="week-bars"><span className="blue">Mathematics<br />08:30</span><span className="green">English<br />10:00</span><span className="orange">Spanish<br />14:00</span><span className="violet">Physics<br />16:00</span></div></section><aside className="card reminder"><Icon tone="orange">♧</Icon><h3>Study reminders</h3><p>{user.reminders ? 'Reminders are on for your next study session.' : 'Study reminders are included with Plus and Pro.'}</p>{!user.reminders && <button className="secondary" onClick={() => go('plans')}>Explore plans</button>}</aside></div><section className="card session-list"><CardTitle icon="▣" title="Today’s sessions" />{sessions.map(s => <div className={`session ${s.done ? 'done' : ''}`} key={s.id}><span className={`dot ${s.color}`} /><div><b>{s.time} · {s.subject}</b><p>{s.task}</p></div><button onClick={() => { setSessions(sessions.map(x => x.id === s.id ? { ...x, done: !x.done } : x)); alert(s.done ? 'Session reopened.' : 'Great work — session completed!') }}>{s.done ? 'Completed' : 'Mark complete'}</button><button className="quiet" onClick={() => { const time = prompt('New start time:', s.time); if (time) { setSessions(sessions.map(x => x.id === s.id ? { ...x, time } : x)); alert('Session moved.') } }}>Move</button></div>)}</section>{modal && <Modal title="Add study session" close={() => setModal(false)}><FormDraft draft={draft} setDraft={setDraft} /><button className="primary full" onClick={save}>Add to my plan</button></Modal>}</>
}
function FormDraft({ draft, setDraft }) { return <div className="form-grid"><label>Time<input value={draft.time} onChange={e => setDraft({ ...draft, time: e.target.value })} /></label><label>Subject<select value={draft.subject} onChange={e => setDraft({ ...draft, subject: e.target.value })}><option>Mathematics</option><option>English</option><option>Spanish</option><option>Physics</option></select></label><label className="span2">Focus<input value={draft.task} onChange={e => setDraft({ ...draft, task: e.target.value })} /></label></div> }

function Practice({ user, consume, alert }) {
  const [tab, setTab] = useState('practice'), [exam, setExam] = useState(null), [config, setConfig] = useState(false), [cards, setCards] = useState([])
  useEffect(() => { generateFlashcards().then(setCards) }, [])
  const makeExam = async (quiz = false) => { if (!consume(quiz ? 'quizzes' : 'exams')) return; const data = await generateMockExam({ subject: quiz ? 'Mixed topics' : 'Mathematics', count: quiz ? 3 : 4 }); setExam(data) }
  if (exam) return <Exam exam={exam} close={() => setExam(null)} />
  return <><PageHeading eyebrow="Build confidence" title="Practice & exams" text="Learn with focused practice, flashcards, and demo mock exams." /><div className="tabs">{[['practice','Practice'],['flashcards','Flashcards'],['history','Exam history']].map(([id, text]) => <button className={tab === id ? 'selected' : ''} onClick={() => setTab(id)} key={id}>{text}</button>)}</div>{tab === 'practice' && <div className="practice-grid"><section className="card feature"><Icon tone="blue">✦</Icon><h2>Quick practice</h2><p>Try a short mixed-topic quiz and keep your study momentum going.</p><button className="primary" onClick={() => makeExam(true)}>Start a quiz</button></section><section className="card feature featured"><span className="popular">DEMO</span><Icon tone="violet">✧</Icon><h2>Mock exam</h2><p>Configure a practice exam built from local demo questions.</p><button className="primary violet-btn" onClick={() => setConfig(true)}>Generate mock exam</button></section><section className="card topics"><h2>Practice by topic</h2>{['Algebra','Reading & analysis','Forces','Spanish vocabulary'].map((x, i) => <button onClick={() => { alert(`Opening ${x} practice.`); makeExam(true) }} key={x}><span className={`dot ${['blue','green','orange','violet'][i]}`} />{x}<i>›</i></button>)}</section></div>}{tab === 'flashcards' && <Flashcards cards={cards} />}{tab === 'history' && <section className="card empty"><Icon tone="green">✓</Icon><h2>Your exam history will appear here</h2><p>Finish a mock exam to start tracking scores and topics to revisit.</p></section>}{config && <ExamConfig close={() => setConfig(false)} start={async data => { setConfig(false); if (consume('exams')) setExam(await generateMockExam(data)) }} />}</>
}
function ExamConfig({ close, start }) { const [draft, setDraft] = useState({ subject: 'Mathematics', topic: 'Algebra', difficulty: 'Medium', count: 4, type: 'Multiple choice' }); return <Modal title="Configure mock exam" close={close}><p className="modal-text">This uses local demo questions. A future AI service can replace this generator.</p><div className="form-grid"><label>Subject<select value={draft.subject} onChange={e => setDraft({ ...draft, subject: e.target.value })}><option>Mathematics</option><option>English</option><option>Spanish</option><option>Physics</option></select></label><label>Topic<select value={draft.topic} onChange={e => setDraft({ ...draft, topic: e.target.value })}><option>Algebra</option><option>Reading & analysis</option><option>Forces</option><option>Vocabulary</option></select></label></div><label className="field">Difficulty<select value={draft.difficulty} onChange={e => setDraft({ ...draft, difficulty: e.target.value })}><option>Easy</option><option>Medium</option><option>Challenging</option></select></label><div className="form-grid"><label>Questions<select value={draft.count} onChange={e => setDraft({ ...draft, count: e.target.value })}><option value="3">3 questions</option><option value="4">4 questions</option></select></label><label>Question type<select value={draft.type} onChange={e => setDraft({ ...draft, type: e.target.value })}><option>Multiple choice</option><option>Written answer</option><option>Mixed</option></select></label></div><button className="primary full" onClick={() => start(draft)}>Create demo exam</button></Modal> }
function Exam({ exam, close }) { const [index, setIndex] = useState(0), [answers, setAnswers] = useState({}), [finished, setFinished] = useState(false); const q = exam.questions[index]; const score = exam.questions.reduce((n, x, i) => n + (answers[i] === x.answer ? 1 : 0), 0); if (finished) return <section className="results card"><Icon tone="green">✓</Icon><p>Exam complete</p><h1>{Math.round(score / exam.questions.length * 100)}%</h1><h2>{score} correct · {exam.questions.length - score} to revisit</h2><div className="score-bar"><span style={{ width: `${score / exam.questions.length * 100}%` }} /></div><p className="modal-text">Try extra practice with Algebra and Forces to build confidence.</p><button className="primary" onClick={close}>Back to practice</button></section>; return <section className="exam card"><div className="exam-top"><button className="quiet" onClick={close}>← Leave exam</button><b>Question {index + 1} of {exam.questions.length}</b></div><div className="exam-progress"><span style={{ width: `${(index + 1) / exam.questions.length * 100}%` }} /></div><small>{q.topic}</small><h1>{q.prompt}</h1><div className="answers">{q.options.map((op, i) => <button key={op} className={answers[index] === i ? 'answer chosen' : 'answer'} onClick={() => setAnswers({ ...answers, [index]: i })}><b>{String.fromCharCode(65 + i)}</b>{op}</button>)}</div><div className="exam-controls"><button className="secondary" disabled={!index} onClick={() => setIndex(index - 1)}>Previous</button>{index < exam.questions.length - 1 ? <button className="primary" onClick={() => setIndex(index + 1)}>Next question</button> : <button className="primary" onClick={() => setFinished(true)}>Finish exam</button>}</div></section> }
function Flashcards({ cards }) { const [current, setCurrent] = useState(0), [flip, setFlip] = useState(false), [known, setKnown] = useState([]); if (!cards.length) return null; const card = cards[current]; const next = (good) => { if (good) setKnown([...known, current]); setFlip(false); setCurrent((current + 1) % cards.length) }; return <section className="flash-wrap"><p>{current + 1} / {cards.length} cards · {known.length} known</p><button className={`flashcard ${flip ? 'flipped' : ''}`} onClick={() => setFlip(!flip)}><small>{flip ? 'BACK' : 'FRONT'}</small><strong>{flip ? card.back : card.front}</strong><span>Click to flip</span></button><div className="flash-controls"><button className="secondary" onClick={() => next(false)}>Needs practice</button><button className="primary" onClick={() => next(true)}>I know this ✓</button></div></section> }

function Settings({ user, setUser, go, alert }) { return <><PageHeading eyebrow="Your space" title="Settings" text="Manage your account, preferences, and subscription." /><div className="settings-grid"><section className="card settings-section"><CardTitle icon="◉" title="Account" /><label className="field">Name<input value={user.name} onChange={e => setUser({ ...user, name: e.target.value })} /></label><label className="field">Email<input value={user.email} onChange={e => setUser({ ...user, email: e.target.value })} /></label><label className="field">Grade<select value={user.grade} onChange={e => setUser({ ...user, grade: e.target.value })}><option>Grade 8</option><option>Grade 9</option><option>Grade 10</option></select></label><button className="secondary" onClick={() => alert('Account details saved.')}>Save changes</button></section><section className="card settings-section"><CardTitle icon="♧" title="Notifications" /><Toggle label="Study reminders" text={user.plan === 'Free' ? 'Included with Plus and Pro' : 'A nudge before each session'} on={user.reminders} disabled={user.plan === 'Free'} toggle={() => setUser({ ...user, reminders: !user.reminders })} /><Toggle label="Exam reminders" text="Keep upcoming exams on your radar" on={true} /><CardTitle icon="◐" title="Appearance" /><Toggle label="Light appearance" text="iStudent is designed for focus" on={true} /></section><section className="card subscription"><span className="plan-tag">Current plan</span><h2>{user.plan}</h2><p>{planInfo[user.plan].price} / month · {user.plan === 'Free' ? 'Basic study tools' : 'More space to learn'}</p><button className="primary" onClick={() => go('plans')}>{user.plan === 'Free' ? 'Upgrade plan' : 'Manage plan'}</button><button className="text-button" onClick={() => { setUser({ ...user, plan: user.plan === 'Free' ? 'Plus' : user.plan === 'Plus' ? 'Pro' : 'Free' }); alert('Demo plan switched.') }}>Switch demo plan</button></section></div><section className="card privacy"><CardTitle icon="▱" title="Privacy" /><p>Your files and progress are saved locally in this prototype. Cloud storage and account data tools will be added with a secure backend.</p></section></> }
function Toggle({ label, text, on, toggle, disabled }) { return <div className="toggle"><div><b>{label}</b><small>{text}</small></div><button aria-label={label} disabled={disabled} className={on ? 'on' : ''} onClick={toggle}><i /></button></div> }

function Plans({ user, setUser, alert, go }) { const choices = [['Free','Get started'],['Plus','Get Plus'],['Pro','Get Pro']]; return <><PageHeading eyebrow="Plans" title="Choose the plan that fits your goals" text="Get more features, more practice, and better results. Upgrade anytime." /><div className="plans">{choices.map(([name, cta]) => { const p = planInfo[name]; return <section className={`plan-card ${name === 'Plus' ? 'recommended' : ''} ${name === 'Pro' ? 'pro' : ''}`} key={name}>{name === 'Plus' && <span className="popular">Most Popular</span>}<Icon tone={p.color}>{name === 'Free' ? '♧' : name === 'Plus' ? '☆' : '♨'}</Icon><h2>{name}</h2><p>{name === 'Free' ? 'Get started and explore iStudent.' : name === 'Plus' ? 'Stay organized, practice more and get better results.' : 'The full iStudent experience. No limits, no distractions.'}</p><h1>{p.price}<small>/month</small></h1><button className={name === 'Pro' ? 'primary violet-btn' : 'primary'} disabled={user.plan === name} onClick={() => { setUser({ ...user, plan: name }); alert(name === 'Free' ? 'You are now on the Free plan.' : `${name} is active in this demo.`); go('home') }}>{user.plan === name ? 'Current plan' : cta}</button><ul><li>▤ Document uploads <b>{limitLabel(p.uploads)}</b></li><li>✦ Personalized mock exams <b>{limitLabel(p.exams)}</b></li><li>? AI-style quizzes <b>{limitLabel(p.quizzes)}</b></li><li>{name === 'Free' ? '○' : '✓'} Study reminders <b>{name === 'Free' ? 'Not included' : 'Included'}</b></li><li>▣ {name === 'Free' ? 'Basic' : 'Personalized'} study plan <b>✓</b></li></ul><div className="plan-footer">{name === 'Free' ? 'A great way to get started with iStudent.' : name === 'Plus' ? 'Everything you need to stay on track.' : 'For students who want the full experience.'}</div></section>})}</div></> }
function Profile({ user, setUser, close, go, alert }) { return <Modal title="Your profile" close={close}><div className="profile-hero"><span>{user.name.split(' ').map(x => x[0]).join('')}</span><h2>{user.name}</h2><p>{user.grade} · {user.school}</p></div><label className="field">School<input value={user.school} onChange={e => setUser({ ...user, school: e.target.value })} /></label><label className="field">Current plan<select value={user.plan} onChange={e => setUser({ ...user, plan: e.target.value })}><option>Free</option><option>Plus</option><option>Pro</option></select></label><button className="primary full" onClick={() => { alert('Profile saved.'); close() }}>Save profile</button><button className="text-button full" onClick={() => { close(); go('plans') }}>View plans</button></Modal> }
function Modal({ title, children, close }) { return <div className="modal-backdrop" onMouseDown={close}><section className="modal" onMouseDown={e => e.stopPropagation()}><button className="modal-close" onClick={close}>×</button><h2>{title}</h2>{children}</section></div> }
function PageHeading({ eyebrow, title, text, action, onAction }) { return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{action && <button className="primary" onClick={onAction}>+ {action}</button>}</div> }

createRoot(document.getElementById('root')).render(<App />)
