import React, { useState } from 'react'
import { BarChart3, BookOpen, Check, ChevronLeft, ChevronRight, FileQuestion, Flag, GraduationCap, Pencil, Plus, RotateCcw, Sparkles, Trash2 } from 'lucide-react'
import { useApp } from '../context/AppContext'
import { AiUnavailable, Button, EmptyState, Field, Modal, PageHeading, formatDate } from '../components/UI'

const nowInput = () => { const date = new Date(); date.setDate(date.getDate() + 7); date.setHours(9,0,0,0); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0,16) }

export default function Practice() {
  const { user, data, create, update, remove, notify } = useApp()
  const [tab, setTab] = useState('exams'), [modal, setModal] = useState(null), [ai, setAi] = useState(false), [selected, setSelected] = useState(null)
  const exams = data?.exams || [], subjects = data?.subjects?.filter(item => !item.archived_at) || [], documents = data?.documents || [], practiceSets = data?.practice_sets || [], results = data?.practice_results || []
  const saveExam = async draft => { const payload = { subject_id: draft.subject_id || null, title: draft.title, exam_at: new Date(draft.exam_at).toISOString(), paper: draft.paper || null, topics: typeof draft.topics === 'string' ? draft.topics.split(',').map(value => value.trim()).filter(Boolean) : draft.topics, notes: draft.notes || null, preparation_progress: Number(draft.progress) }; draft.id ? await update('exams', draft.id, payload) : await create('exams', { user_id: user.id, ...payload }); setModal(null); notify(draft.id ? 'Exam updated.' : 'Exam added.') }
  const completeExam = async exam => { await update('exams', exam.id, { completed_at: exam.completed_at ? null : new Date().toISOString() }); notify(exam.completed_at ? 'Exam reopened.' : 'Exam marked complete.') }
  if (selected?.kind === 'quiz') return <QuizRunner quiz={selected} onClose={() => setSelected(null)} />
  if (selected?.kind === 'flashcards') return <FlashcardPlayer set={selected} onClose={() => setSelected(null)} />
  return <>
    <PageHeading eyebrow="Practice & exams" title="Build confidence from your material" text="Track real exams now. AI practice will use only the school material you choose." actions={<Button onClick={() => setModal('exam')}><Plus /> Add exam</Button>} />
    <div className="tabs practice-tabs">{[['exams', GraduationCap, 'Exams'], ['quizzes', FileQuestion, 'Quizzes'], ['flashcards', BookOpen, 'Flashcards'], ['mock', Flag, 'Mock exams'], ['results', BarChart3, 'Results']].map(([id, Icon, label]) => <button className={tab === id ? 'active' : ''} onClick={() => setTab(id)} key={id}><Icon />{label}</button>)}</div>
    {tab === 'exams' && <section className="card list-card"><div className="section-heading"><div><h2>Exam list</h2><p>Countdowns use your local date and time.</p></div><Button variant="secondary" onClick={() => setModal('schedule')}><Sparkles /> Extract schedule</Button></div>{exams.length ? <div className="exam-list">{exams.sort((a,b) => new Date(a.exam_at)-new Date(b.exam_at)).map(exam => { const days = Math.ceil((new Date(exam.exam_at) - new Date()) / 86400000); return <article className={exam.completed_at ? 'completed' : ''} key={exam.id}><time><b>{new Date(exam.exam_at).getDate()}</b><small>{new Date(exam.exam_at).toLocaleString([], { month: 'short' })}</small></time><div><b>{exam.title}</b><p>{exam.subjects?.name || 'No subject'}{exam.paper ? ` · ${exam.paper}` : ''}</p>{exam.topics?.length > 0 && <small>{exam.topics.join(' · ')}</small>}</div><div className="exam-progress"><span style={{ width: `${exam.preparation_progress || 0}%` }} /><small>{exam.preparation_progress || 0}% prepared</small></div><em>{exam.completed_at ? 'Complete' : days < 0 ? 'Past' : days === 0 ? 'Today' : `${days} days`}</em><button className="round-button" onClick={() => completeExam(exam)}><Check /></button><button className="round-button" onClick={() => setModal({ type: 'exam', item: exam })}><Pencil /></button><button className="delete-button" onClick={() => remove('exams', exam.id)}><Trash2 /></button></article>})}</div> : <EmptyState icon={GraduationCap} title="No exams added yet" text="Upload an exam schedule or add an exam manually."><div className="inline-actions"><Button onClick={() => setModal('exam')}>Add an exam</Button><Button variant="secondary" onClick={() => setModal('schedule')}>Upload schedule</Button></div></EmptyState>}</section>}
    {tab === 'quizzes' && <PracticeLibrary icon={FileQuestion} title="No quizzes yet" text="Upload study material first, then configure a quiz from a document, subject or topic." button="Generate quiz" sets={practiceSets.filter(item => item.kind === 'quiz')} onSelect={setSelected} onGenerate={() => setModal('quiz')} />}
    {tab === 'flashcards' && <PracticeLibrary icon={BookOpen} title="No flashcard sets yet" text="Generate a focused set from your own notes or create cards manually in the next AI-enabled phase." button="Generate flashcards" sets={practiceSets.filter(item => item.kind === 'flashcards')} onSelect={setSelected} onGenerate={() => setModal('flashcards')} />}
    {tab === 'mock' && <section className="practice-builder"><div className="practice-intro violet"><span className="icon-bubble"><Flag /></span><span className="eyebrow">IGCSE-style practice</span><h2>Configure a mock exam</h2><p>Choose source material, paper details, difficulty, length and question style. Nothing is generated until AI is securely connected.</p><Button onClick={() => setModal('mock')}>Configure mock exam</Button></div><div className="card safeguard"><Sparkles /><h3>Built around your material</h3><p>Future mock exams will be grounded in the documents you select, not generic internet questions.</p><ul><li><Check />Question paper</li><li><Check />Mark scheme</li><li><Check />Timed exam mode</li><li><Check />Topic-level feedback</li></ul></div></section>}
    {tab === 'results' && <section className="card list-card">{results.length ? <div>{results.map(result => <div key={result.id}>{result.score_percent}%</div>)}</div> : <EmptyState icon={BarChart3} title="No practice results yet" text="Completed quizzes and mock exams will appear here without invented scores." />}</section>}
    {(modal === 'exam' || modal?.type === 'exam') && <ExamModal initial={modal.item} subjects={subjects} onClose={() => setModal(null)} onSave={saveExam} />}
    {['quiz','flashcards','mock'].includes(modal) && <GeneratorModal type={modal} subjects={subjects} documents={documents} onClose={() => setModal(null)} onContinue={() => { setModal(null); setAi(true) }} />}
    {modal === 'schedule' && <Modal title="Upload an exam schedule" description="Store a PDF, image or Word document now. AI extraction will stay disabled until integration is enabled." onClose={() => setModal(null)}><p className="muted">Use Upload Document and choose “Exam schedule” as the document type.</p><Button className="full" onClick={() => location.assign('/upload')}>Go to upload</Button></Modal>}{ai && <AiUnavailable onClose={() => setAi(false)} />}
  </>
}

function PracticeLibrary({ icon: Icon, title, text, button, sets, onSelect, onGenerate }) { return <section className="card list-card">{sets.length ? <div className="practice-set-grid">{sets.map(set => <button key={set.id} onClick={() => onSelect(set)}><Icon /><b>{set.title}</b><small>{set.items?.length || 0} items</small></button>)}</div> : <EmptyState icon={Icon} title={title} text={text}><Button onClick={onGenerate}>{button}</Button></EmptyState>}</section> }

function ExamModal({ initial, subjects, onClose, onSave }) { const localInput = value => value ? new Date(new Date(value).getTime() - new Date(value).getTimezoneOffset() * 60000).toISOString().slice(0,16) : nowInput(); const [draft, setDraft] = useState(initial ? { ...initial, exam_at: localInput(initial.exam_at), topics: initial.topics?.join(', ') || '', progress: initial.preparation_progress } : { title: '', subject_id: '', exam_at: nowInput(), paper: '', topics: '', notes: '', progress: 0 }), [saving, setSaving] = useState(false); const submit = async event => { event.preventDefault(); setSaving(true); try { await onSave(draft) } finally { setSaving(false) } }; return <Modal title={initial ? 'Edit exam' : 'Add exam'} onClose={onClose}><form onSubmit={submit} className="modal-form"><Field label="Exam name"><input required value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} placeholder="e.g. Chemistry Paper 2" /></Field><Field label="Subject"><select value={draft.subject_id || ''} onChange={e => setDraft({ ...draft, subject_id: e.target.value })}><option value="">No subject</option>{subjects.map(subject => <option key={subject.id} value={subject.id}>{subject.name}</option>)}</select></Field><Field label="Date and time"><input required type="datetime-local" value={draft.exam_at} onChange={e => setDraft({ ...draft, exam_at: e.target.value })} /></Field><div className="form-grid"><Field label="Paper"><input value={draft.paper || ''} onChange={e => setDraft({ ...draft, paper: e.target.value })} placeholder="Paper 1" /></Field><Field label="Preparation"><input type="number" min="0" max="100" value={draft.progress} onChange={e => setDraft({ ...draft, progress: e.target.value })} /></Field></div><Field label="Topics or material" hint="Separate topics with commas."><input value={draft.topics} onChange={e => setDraft({ ...draft, topics: e.target.value })} /></Field><Field label="Notes"><textarea value={draft.notes || ''} onChange={e => setDraft({ ...draft, notes: e.target.value })} /></Field><Button className="full" loading={saving}>{initial ? 'Save changes' : 'Add exam'}</Button></form></Modal> }

function GeneratorModal({ type, subjects, documents, onClose, onContinue }) { const labels = { quiz: 'Configure quiz', flashcards: 'Configure flashcards', mock: 'Configure mock exam' }; const [draft, setDraft] = useState({ document: '', subject: '', topic: '', difficulty: 'Medium', count: type === 'quiz' ? 10 : type === 'flashcards' ? 20 : 20, questionTypes: ['Multiple choice'] }); return <Modal title={labels[type]} description="Choose the source and format. The next step is intentionally disabled until AI is connected." onClose={onClose} wide><div className="form-grid"><Field label="Source document"><select value={draft.document} onChange={e => setDraft({ ...draft, document: e.target.value })}><option value="">Choose a document</option>{documents.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Field><Field label="Subject"><select value={draft.subject} onChange={e => setDraft({ ...draft, subject: e.target.value })}><option value="">Choose a subject</option>{subjects.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Field><Field label="Topic"><input value={draft.topic} onChange={e => setDraft({ ...draft, topic: e.target.value })} placeholder="Optional focus" /></Field><Field label="Difficulty"><select value={draft.difficulty} onChange={e => setDraft({ ...draft, difficulty: e.target.value })}><option>Easy</option><option>Medium</option><option>Challenging</option></select></Field><Field label={type === 'flashcards' ? 'Cards' : 'Questions'}><input type="number" min="5" max="100" value={draft.count} onChange={e => setDraft({ ...draft, count: e.target.value })} /></Field>{type !== 'flashcards' && <Field label="Question style"><select><option>Mixed</option><option>Multiple choice</option><option>Short answer</option><option>True / false</option></select></Field>}</div><Button className="full" onClick={onContinue} disabled={!draft.document}>Continue</Button></Modal> }

export function QuizRunner({ quiz, onClose }) { const questions = quiz.items || [], [index, setIndex] = useState(0), [answers, setAnswers] = useState({}), [finished, setFinished] = useState(false); if (!questions.length) return <EmptyState icon={FileQuestion} title="This quiz has no questions" text="No generated content is stored for this quiz."><Button onClick={onClose}>Return to quizzes</Button></EmptyState>; const current = questions[index]; const score = questions.reduce((total, item, i) => total + (answers[i] === item.correct_index ? 1 : 0), 0); if (finished) return <section className="card quiz-runner results"><Check /><h1>{Math.round(score / questions.length * 100)}%</h1><p>{score} of {questions.length} correct</p><Button onClick={onClose}>Finish</Button></section>; return <section className="card quiz-runner"><header><button onClick={onClose}><ChevronLeft /> Exit</button><span>Question {index + 1} of {questions.length}</span></header><div className="progress-bar"><span style={{ width: `${(index + 1) / questions.length * 100}%` }} /></div><h2>{current.prompt}</h2><div className="quiz-options">{current.options?.map((option, i) => <button className={answers[index] === i ? 'selected' : ''} onClick={() => setAnswers({ ...answers, [index]: i })} key={option}><b>{String.fromCharCode(65+i)}</b>{option}</button>)}</div><footer><Button variant="ghost" disabled={index === 0} onClick={() => setIndex(index - 1)}>Previous</Button><Button disabled={answers[index] === undefined} onClick={() => index === questions.length - 1 ? setFinished(true) : setIndex(index + 1)}>{index === questions.length - 1 ? 'Submit quiz' : 'Next'} <ChevronRight /></Button></footer></section> }

export function FlashcardPlayer({ set, onClose }) { const cards = set.items || [], [index, setIndex] = useState(0), [flipped, setFlipped] = useState(false); if (!cards.length) return <EmptyState icon={BookOpen} title="This set has no cards" text="No generated content is stored for this set."><Button onClick={onClose}>Return to flashcards</Button></EmptyState>; return <section className="flashcard-player"><header><button onClick={onClose}><ChevronLeft /> Exit</button><span>{index + 1} / {cards.length}</span></header><button className={`study-card ${flipped ? 'flipped' : ''}`} onClick={() => setFlipped(!flipped)}><small>{flipped ? 'BACK' : 'FRONT'}</small><strong>{flipped ? cards[index].back : cards[index].front}</strong><span><RotateCcw /> Click to flip</span></button><footer><Button variant="secondary" onClick={() => { setIndex((index - 1 + cards.length) % cards.length); setFlipped(false) }}>Need practice</Button><Button onClick={() => { setIndex((index + 1) % cards.length); setFlipped(false) }}>Know it</Button></footer></section> }
