import React, { useState } from 'react'
import { Archive, Bell, Check, CircleUserRound, CreditCard, KeyRound, Moon, Palette, Plus, Shield, Sun, Trash2 } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { useApp } from '../context/AppContext'
import { saveProfile } from '../lib/data'
import { appUrl, supabase } from '../lib/supabase'
import { Button, Field, Modal, PageHeading } from '../components/UI'

const subjectColors = ['#2692f5', '#2fc77b', '#9a5cf0', '#ffad2f', '#f04d92', '#16b8b1']

export default function Settings() {
  const { user, profile, data, refresh, notify, theme, setTheme, create, update } = useApp()
  const navigate = useNavigate()
  const [draft, setDraft] = useState({ display_name: profile?.display_name || '', grade_year: profile?.grade_year || '', school_system: profile?.school_system || '', timezone: profile?.timezone || Intl.DateTimeFormat().resolvedOptions().timeZone }), [saving, setSaving] = useState(false), [subjectModal, setSubjectModal] = useState(false), [deleteModal, setDeleteModal] = useState(false)
  const subjects = data?.subjects || []
  const save = async event => { event.preventDefault(); setSaving(true); try { await saveProfile(user.id, draft); await refresh(); notify('Profile updated.') } catch (error) { notify(error.message, 'error') } finally { setSaving(false) } }
  const togglePref = async (key, value) => { try { await saveProfile(user.id, { [key]: value }); await refresh(); notify('Preference saved.') } catch (error) { notify(error.message, 'error') } }
  const deleteAccount = async () => { const { data: sessionData } = await supabase.auth.getSession(); const response = await fetch('/api/account', { method: 'DELETE', headers: { Authorization: `Bearer ${sessionData.session?.access_token || ''}` } }); if (!response.ok) { const result = await response.json(); return notify(result.error || 'Unable to delete account.', 'error') } await supabase.auth.signOut() }
  const chooseTheme = async value => { setTheme(value); try { await saveProfile(user.id, { theme_preference: value }); await refresh() } catch (error) { notify(error.message, 'error') } }
  return <>
    <PageHeading eyebrow="Settings" title="Make iStudent yours" text="Manage your profile, subjects, preferences, privacy and account." />
    <div className="settings-layout"><section className="card settings-card"><div className="settings-title"><span className="icon-bubble blue"><CircleUserRound /></span><div><h2>Profile</h2><p>Your private account information.</p></div></div><form onSubmit={save}><div className="form-grid"><Field label="Name"><input value={draft.display_name} onChange={e => setDraft({ ...draft, display_name: e.target.value })} /></Field><Field label="Grade or year"><input value={draft.grade_year} onChange={e => setDraft({ ...draft, grade_year: e.target.value })} /></Field><Field label="School system"><select value={draft.school_system} onChange={e => setDraft({ ...draft, school_system: e.target.value })}><option value="">Choose one</option>{['IGCSE','GCSE','IB','A-Level','AP','Other'].map(item => <option key={item}>{item}</option>)}</select></Field><Field label="Timezone"><input value={draft.timezone} readOnly /></Field></div><Field label="Email" hint="Email changes require verification."><input value={user?.email || ''} readOnly /></Field><Button loading={saving}>Save profile</Button></form></section>
      <section className="card settings-card"><div className="settings-title"><span className="icon-bubble violet"><Palette /></span><div><h2>Appearance</h2><p>Choose a calm workspace in any light.</p></div></div><div className="theme-options">{[['light', Sun, 'Light'], ['dark', Moon, 'Dark'], ['system', Palette, 'System']].map(([id, Icon, label]) => <button className={theme === id ? 'selected' : ''} onClick={() => chooseTheme(id)} key={id}><Icon /><b>{label}</b>{theme === id && <Check />}</button>)}</div><div className="settings-title subsection"><span className="icon-bubble green"><Bell /></span><div><h2>Notifications</h2><p>Use reminders that help, not distract.</p></div></div><Toggle label="Study reminders" text="Remind me before a planned session." value={profile?.study_reminders} onChange={value => togglePref('study_reminders', value)} /><Toggle label="Exam reminders" text="Alert me as real exam dates approach." value={profile?.exam_reminders ?? true} onChange={value => togglePref('exam_reminders', value)} /><Toggle label="Achievement updates" text="Tell me when genuine progress unlocks an achievement." value={profile?.achievement_notifications ?? true} onChange={value => togglePref('achievement_notifications', value)} /></section>
      <section className="card settings-card subjects-settings"><div className="section-heading"><div className="settings-title"><span className="icon-bubble orange"><CreditCard /></span><div><h2>Subjects</h2><p>Keep only what you’re actually studying.</p></div></div><Button variant="secondary" onClick={() => setSubjectModal(true)}><Plus /> Add</Button></div><div className="subject-list">{subjects.map(subject => <div className={subject.archived_at ? 'archived' : ''} key={subject.id}><i style={{ background: subject.color }} /><span><b>{subject.name}</b><small>{subject.archived_at ? 'Archived' : 'Active'}</small></span><button onClick={() => update('subjects', subject.id, { archived_at: subject.archived_at ? null : new Date().toISOString() })} aria-label={subject.archived_at ? 'Restore subject' : 'Archive subject'}><Archive /></button></div>)}</div></section>
      <section className="card settings-card"><div className="settings-title"><span className="icon-bubble green"><CreditCard /></span><div><h2>Plan & billing</h2><p>Your subscription is verified by the server.</p></div></div><div className="current-plan"><span>{profile?.subscription_plan || 'Free'}</span><div><b>{profile?.subscription_plan || 'Free'} plan</b><p>{profile?.subscription_plan === 'free' || !profile?.subscription_plan ? 'Explore more features when you need them.' : 'Manage your secure Stripe subscription.'}</p></div></div><Button variant="secondary" onClick={() => navigate('/plans')}>Compare plans</Button><div className="settings-title subsection"><span className="icon-bubble blue"><KeyRound /></span><div><h2>Security</h2><p>Password and account controls.</p></div></div><Button variant="secondary" onClick={() => supabase.auth.resetPasswordForEmail(user.email, { redirectTo: appUrl('/auth/reset') })}>Send password reset email</Button></section>
    </div>
    <section className="card danger-zone"><div><Shield /><span><b>Privacy and account</b><p>Your date of birth, school data and documents are never public.</p></span></div><Button variant="danger" onClick={() => setDeleteModal(true)}><Trash2 /> Delete account</Button></section>
    {subjectModal && <SubjectModal userId={user.id} onClose={() => setSubjectModal(false)} create={create} notify={notify} />}{deleteModal && <Modal title="Delete your account?" description="This permanently removes your profile, school data and uploaded files. It cannot be undone." onClose={() => setDeleteModal(false)}><Button variant="danger" className="full" onClick={deleteAccount}>Permanently delete my account</Button></Modal>}
  </>
}

function Toggle({ label, text, value, onChange }) { return <div className="toggle-row"><span><b>{label}</b><small>{text}</small></span><button role="switch" aria-checked={Boolean(value)} className={value ? 'on' : ''} onClick={() => onChange(!value)}><i /></button></div> }
function SubjectModal({ userId, onClose, create, notify }) { const [name, setName] = useState(''), [color, setColor] = useState(subjectColors[0]), [saving, setSaving] = useState(false); const submit = async event => { event.preventDefault(); setSaving(true); try { await create('subjects', { user_id: userId, name: name.trim(), color, icon: 'book' }); notify('Subject added.'); onClose() } finally { setSaving(false) } }; return <Modal title="Add subject" onClose={onClose}><form onSubmit={submit}><Field label="Subject name"><input autoFocus required value={name} onChange={e => setName(e.target.value)} /></Field><Field label="Colour"><div className="color-picker">{subjectColors.map(value => <button type="button" className={color === value ? 'selected' : ''} style={{ background: value }} onClick={() => setColor(value)} key={value}>{color === value && <Check />}</button>)}</div></Field><Button className="full" loading={saving}>Add subject</Button></form></Modal> }
